# Puerto del servicio-de-cuentas
spring:  
  application:
    name: servicio-de-cuentas
# Puerto servicio-de-cuentas
server:
  port: ${PORT:9020}
#
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_URL:http://localhost:3010/eureka/}

logging:
  level:
   com.netflix: DEBUG
   org.springframework.cloud: DEBUG
   com.netflix.eureka: OFF
   com.netflix.discovery: OFF
    