
spring:  
  application:
    name: servicio-de-pedidos

server:
  port: ${PORT:9010}  


servicio-de-cuentas:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9020
#
servicio-de-clientes:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9030
#
servicio-de-productos:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:9040