#
spring:  
  application:
    name: servicio-de-productos
# Puerto servicio-de-productos
server:
  port: ${PORT:9040}
#
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:3010/eureka/}