#
spring:  
  application:
    name: servicio-de-clientes
# Puerto servicio-de-clientes
server:
  port: ${PORT:9030}
#
eureka:  client:    service-url:      defaultZone: ${EUREKA_URL:http://localhost:3010/eureka/}