#
spring:  
  application:
    name: servicio-de-clientes
#
---
spring:
  profiles: zona1
eureka:
  instance:
    metadataMap:
      zone: zona1
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
      preferSameZoneEureka: true
server:  
  port: ${PORT:9030}

---
spring:
  profiles: zona2
eureka:
  instance:
    metadataMap:
      zone: zona2
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
      preferSameZoneEureka: true
server:  
  port: ${PORT:9031}